spring.application.name=todo-list
# Habilitar la consola de H2 para ver las tablas en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de la conexión
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Actualizar el esquema automáticamente cada vez que cambies una clase @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true