spring.application.name=todo-list
# Habilitar la consola de H2 para ver las tablas en el navegador
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Configuración de la conexiónspring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
## Esto es clave para que no falle al no encontrar tablas
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true